/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2024-05-09 16:57:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import models.BrandModel;

public final class AddProducts_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/pages/AdminSidebar.jsp", Long.valueOf(1715207774726L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("models.BrandModel");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<title>Add Product</title>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("body {\n");
      out.write("    font-family: Arial, sans-serif;\n");
      out.write("    background-color: #f6f6f9;\n");
      out.write("    color: #363949;\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container {\n");
      out.write("    width: 1000px;\n");
      out.write("    margin: 0 auto;\n");
      out.write("    margin-top: 50px;\n");
      out.write("    padding: 20px;\n");
      out.write("    background-color: #fff;\n");
      out.write("    border-radius: 32px;\n");
      out.write("    box-shadow: 0 32px 48px rgba(132, 139, 200, 0.18);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-messages {\n");
      out.write("    margin-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".success-message, .error-message {\n");
      out.write("    padding: 10px;\n");
      out.write("    margin-bottom: 10px;\n");
      out.write("    border-radius: 6.4px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".success-message {\n");
      out.write("    background-color: #41f1b6;\n");
      out.write("    color: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".error-message {\n");
      out.write("    background-color: #ff7782;\n");
      out.write("    color: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write("h2 {\n");
      out.write("    font-size: 24px;\n");
      out.write("    font-weight: bold;\n");
      out.write("    color: #333;\n");
      out.write("    margin-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-group {\n");
      out.write("    margin-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-group label {\n");
      out.write("    display: block;\n");
      out.write("    font-weight: bold;\n");
      out.write("    margin-bottom: 10px;\n");
      out.write("    color: #333;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-group input[type=\"text\"],\n");
      out.write(".form-group input[type=\"number\"],\n");
      out.write(".form-group textarea,\n");
      out.write(".form-group select {\n");
      out.write("    width: 40%;\n");
      out.write("    padding: 10px;\n");
      out.write("    border: 1px solid #7d8da1;\n");
      out.write("    border-radius: 6.4px;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-group select {\n");
      out.write("    appearance: none;\n");
      out.write("    background: url('data:image/svg+xml;utf8,<svg fill=\"%237d8da1\" height=\"24\" viewBox=\"0 0 24 24\" width=\"24\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M7 10l5 5 5-5z\"/><path d=\"M0 0h24v24H0z\" fill=\"none\"/></svg>') no-repeat right 10px center/14px auto;\n");
      out.write("    padding-right: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-group button {\n");
      out.write("    padding: 10px 20px;\n");
      out.write("    border: none;\n");
      out.write("    border-radius: 6.4px;\n");
      out.write("    background-color: cornflowerblue;\n");
      out.write("    color: #fff;\n");
      out.write("    cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-group button:hover {\n");
      out.write("    background-color: #111e88;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body style=\"display:flex; justify-content:space-between;\"> \n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Admin Side Bar</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap\"rel=\"stylesheet\"/>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons+Outlined\" rel=\"stylesheet\"/>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/AdminSidebar.css\"/>\n");
      out.write("    \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div style=\"width:400px;\">\n");
      out.write("	      <aside id=\"sidebar\">\n");
      out.write("        <div class=\"sidebar-title\">\n");
      out.write("          <div class=\"sidebar-brand\">\n");
      out.write("            <span class=\"material-icons-outlined\">shopping_cart</span\n");
      out.write("            >Pixelprinter\n");
      out.write("          </div>\n");
      out.write("          <span class=\"material-icons-outlined\" onclick=\"closeSidebar()\"\n");
      out.write("            >close</span>\n");
      out.write("        </div>\n");
      out.write(" <ul class=\"sidebar-list\">\n");
      out.write("    <li class=\"sidebar-list-item\">\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AddProductServlet\">\n");
      out.write("            <span class=\"material-icons-outlined\">print</span> Add Product\n");
      out.write("        </a>\n");
      out.write("    </li>\n");
      out.write("    <li class=\"sidebar-list-item\">\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/DisplayProductServlet\">\n");
      out.write("            <span class=\"material-icons-outlined\">inventory_2</span> Products\n");
      out.write("        </a>\n");
      out.write("    </li>\n");
      out.write("    <li class=\"sidebar-list-item\">\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AddBrand\">\n");
      out.write("            <span class=\"material-icons-outlined\">category</span> Add Categories\n");
      out.write("        </a>\n");
      out.write("    </li>\n");
      out.write("    <li class=\"sidebar-list-item\">\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/DisplayUserDetailsServlet\">\n");
      out.write("            <span class=\"material-icons-outlined\">group</span> Customers\n");
      out.write("        </a>\n");
      out.write("    </li>\n");
      out.write("    <li class=\"sidebar-list-item\">\n");
      out.write("        <a href=\"inventory.jsp\">\n");
      out.write("        	<span class=\"material-icons-outlined\">mark_email_unread</span> Messages\n");
      out.write("        </a>\n");
      out.write("    </li>\n");
      out.write("        <li class=\"sidebar-list-item\">\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pages/AddAdmin.jsp\">\n");
      out.write("            <span class=\"material-icons-outlined\">person_add</span> Add Admin\n");
      out.write("        </a>\n");
      out.write("    </li>\n");
      out.write("    <li class=\"sidebar-list-item\">\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AdminSalesReportServlet\">\n");
      out.write("            <span class=\"material-icons-outlined\">view_kanban</span> Reports\n");
      out.write("        </a>\n");
      out.write("    </li>\n");
      out.write("        <li class=\"sidebar-list-item\">\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogoutServlet\">\n");
      out.write("            <span class=\"material-icons-outlined\">logout</span> Logout\n");
      out.write("        </a>\n");
      out.write("    </li>\n");
      out.write("</ul>\n");
      out.write("      </aside>\n");
      out.write("	</div>\n");
      out.write("	    <script\n");
      out.write("      type=\"text/javascript\"\n");
      out.write("      src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/AdminHome.js\"\n");
      out.write("    ></script>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"form-messages\">\n");
      out.write("			");

			if (request.getAttribute("successMessage") != null) {
			
      out.write("\n");
      out.write("			<div class=\"success-message\">");
      out.print(request.getAttribute("successMessage"));
      out.write("</div>\n");
      out.write("			");

			} else if (request.getAttribute("errorMessage") != null) {
			
      out.write("\n");
      out.write("			<div class=\"error-message\">");
      out.print(request.getAttribute("errorMessage"));
      out.write("</div>\n");
      out.write("			");

			}
			
      out.write("\n");
      out.write("		</div>\n");
      out.write("		<h2>Add Product</h2>\n");
      out.write("		<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AddProductServlet\"\n");
      out.write("			method=\"POST\" enctype=\"multipart/form-data\">\n");
      out.write("			<div style= \"display:flex; \">\n");
      out.write("			<div style=\"width:1200px;\">\n");
      out.write("			<div class=\"form-group\">\n");
      out.write("				<label for=\"productName\">Product Name</label> <input type=\"text\"\n");
      out.write("					id=\"productName\" name=\"productName\" required>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"form-group\">\n");
      out.write("				<label for=\"productDescription\">Product Description</label>\n");
      out.write("				<textarea id=\"productDescription\" name=\"productDescription\" rows=\"4\"\n");
      out.write("					required></textarea>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"form-group\">\n");
      out.write("				<label for=\"productPrice\">Price</label> <input type=\"text\"\n");
      out.write("					id=\"productPrice\" name=\"productPrice\" required>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"form-group\">\n");
      out.write("				<label for=\"productQuantity\">Quantity</label> <input type=\"number\"\n");
      out.write("					id=\"productQuantity\" name=\"productQuantity\" required>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"form-group\">\n");
      out.write("				<label for=\"productImage\">Product Image</label> <input type=\"file\"\n");
      out.write("					id=\"productImage\" name=\"productImage\" accept=\"image/*\" required>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"form-group\">\n");
      out.write("				<label for=\"brandName\">Brand</label> <select id=\"brandName\"\n");
      out.write("					name=\"brandName\" required>\n");
      out.write("					<option value=\"\" selected disabled>Select Brand</option>\n");
      out.write("					");

					if (request.getAttribute("brands") != null) {
						List<BrandModel> brands = (List<BrandModel>) request.getAttribute("brands");
						for (BrandModel brand : brands) {
					
      out.write("\n");
      out.write("					<option value=\"");
      out.print(brand.getCompanyName());
      out.write('"');
      out.write('>');
      out.print(brand.getCompanyName());
      out.write("</option>\n");
      out.write("					");

					}
					}
					
      out.write("\n");
      out.write("				</select>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<div style=\"width:1000px; \">\n");
      out.write("			<div class=\"form-group\">\n");
      out.write("				<label for=\"printTechnology\">Print Technology</label> <select\n");
      out.write("					id=\"printTechnology\" name=\"printTechnology\" required>\n");
      out.write("					<option value=\"\" selected disabled>Select Print Technology</option>\n");
      out.write("					<option value=\"Inkjet\">Inkjet</option>\n");
      out.write("					<option value=\"Laser\">Laser</option>\n");
      out.write("					<option value=\"LED\">LED</option>\n");
      out.write("					<option value=\"Dot Matrix\">Dot Matrix</option>\n");
      out.write("					<option value=\"Dye Sublimation\">Dye Sublimation</option>\n");
      out.write("				</select>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"form-group\">\n");
      out.write("				<label for=\"printColor\">Print Color</label> <select id=\"printColor\"\n");
      out.write("					name=\"printColor\" required>\n");
      out.write("					<option value=\"\" selected disabled>Select Print Color</option>\n");
      out.write("					<option value=\"Black and white\">Black and White</option>\n");
      out.write("					<option value=\"Color\">Color</option>\n");
      out.write("					<option value=\"Supports Both\">Supports Both</option>\n");
      out.write("				</select>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"form-group\">\n");
      out.write("				<label for=\"printSpeed\">Print Speed (e.g., \"500ppm\")</label> <input\n");
      out.write("					type=\"text\" id=\"printSpeed\" name=\"printSpeed\" required>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"form-group\">\n");
      out.write("				<label for=\"printResolution\">Print Resolution</label> <input\n");
      out.write("					type=\"text\" id=\"printResolution\" name=\"printResolution\" required>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"form-group\">\n");
      out.write("				<label for=\"printerWeight\">Printer Weight</label> <input type=\"text\" id=\"weight\"\n");
      out.write("					name=\"printerWeight\" required>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"form-group\">\n");
      out.write("				<label for=\"printerDimensions\">Printer Dimensions</label> <input type=\"text\"\n");
      out.write("					id=\"printerDimensions\" name=\"printerDimensions\" required>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"form-group\">\n");
      out.write("				<label for=\"operatingSystem\">Operating Systems</label> <input\n");
      out.write("					type=\"text\" id=\"operatingSystem\" name=\"operatingSystem\" required>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"form-group\">\n");
      out.write("				<label for=\"printerColor\">Printer Color</label> <input type=\"text\" id=\"printerColor\"\n");
      out.write("					name=\"printerColor\" required>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"form-group\">\n");
      out.write("				<label for=\"supportedPageSize\">Supported Page Size</label> <input\n");
      out.write("					type=\"text\" id=\"supportedPageSize\" name=\"supportedPageSize\"\n");
      out.write("					required>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		</div>\n");
      out.write("			<button type=\"submit\">Add Product</button>\n");
      out.write("		</form>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
