/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2024-05-14 08:43:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import utils.Utilities;
import java.util.List;
import models.UserCartModel;

public final class Cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/pages/Header.jsp", Long.valueOf(1715671287572L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("utils.Utilities");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("models.UserCartModel");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<link rel=\"icon\"\n");
      out.write("    href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Images/pixelprinter-high-resolution-logo.png\"\n");
      out.write("    type=\"image/png\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<title>\n");
      out.write("    ");
      out.write("\n");
      out.write("    Printer Design\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");
 String currentPage = request.getRequestURI();
       if (currentPage.endsWith("Index.jsp")) { 
      out.write("\n");
      out.write("           | Home\n");
      out.write("       ");
 } else if (currentPage.endsWith("DisplayProductToCustomerServlet")) { 
      out.write("\n");
      out.write("           | Product\n");
      out.write("       ");
 } else if (currentPage.endsWith("Contact.jsp")) { 
      out.write("\n");
      out.write("           | About Us\n");
      out.write("       ");
 } else if (currentPage.endsWith("Login.jsp")) { 
      out.write("\n");
      out.write("           | Login\n");
      out.write("       ");
 } else if (currentPage.endsWith("LogoutServlet")) { 
      out.write("\n");
      out.write("           | Logout\n");
      out.write("       ");
 } 
      out.write("\n");
      out.write("</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("    href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("    href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/Header.css\" />\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    <section id=\"header\" class=\"header\">\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pages/Index.jsp\"><img\n");
      out.write("            src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Images/logo.png\" class=\"logo\"\n");
      out.write("            style=\"width: 120px; height: auto;\"></a>\n");
      out.write("        <nav class=\"navbar\">\n");
      out.write("            <a class=\"active\"\n");
      out.write("                href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pages/Index.jsp\">Home</a> <a\n");
      out.write("                href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/DisplayProductToCustomerServlet\">Product</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pages/Contact.jsp\">About\n");
      out.write("                Us</a> \n");
      out.write("            ");
 
            if (session.getAttribute("username") == null) {
            
      out.write("\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pages/Login.jsp\">Login</a>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogoutServlet\">Logout</a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </nav>\n");
      out.write("        \n");
      out.write("        <div class=\"icons\">\n");
      out.write("            <div id=\"menu-btn\" class=\"fas fa-bars\"></div>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/UserProfile\" class=\"fas fa-user-circle\"></a> \n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/SearchServlet\" class=\"fas fa-search\"></a> \n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/DisplayCart\" class=\"fas fa-shopping-cart\"></a>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Add To Cart</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/Cart.css\">\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <script src=\"https://kit.fontawesome.com/11d376cef2.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container mt-5\">\n");
      out.write("        <h1 class=\"text-left mb-5\">User Cart </h1>\n");
      out.write("        <div class=\"row\">\n");
      out.write("            ");
 
            List<UserCartModel> userCartDetails = (List<UserCartModel>) request.getAttribute("userCartDetails");
            if (userCartDetails != null && !userCartDetails.isEmpty()) {
                for (UserCartModel cartItem : userCartDetails) {
            
      out.write("\n");
      out.write("            <div class=\"col-md-6 col-lg-4 mb-4\">\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Uploads/ProductImages/");
      out.print( cartItem.getProductImage() );
      out.write("\" class=\"card-img-top\" alt=\"");
      out.print( cartItem.getProductName() );
      out.write("\">\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <h5 class=\"card-title\">");
      out.print( cartItem.getProductName() );
      out.write("</h5>\n");
      out.write("                        <p class=\"card-text\">Quantity: <span id=\"quantity_");
      out.print( cartItem.getProductId() );
      out.write('"');
      out.write('>');
      out.print( cartItem.getQuantity() );
      out.write("</span></p>\n");
      out.write("                        <p class=\"card-text\">Price: ");
      out.print( cartItem.getPrice() );
      out.write("</p>\n");
      out.write("                        <div class=\"d-flex justify-content-between\">\n");
      out.write("                            <div class=\"quantity-control\">\n");
      out.write("                                <button onclick=\"decreaseQuantity(");
      out.print( cartItem.getProductId() );
      out.write(")\" class=\"btn btn-sm btn-outline-primary\">-</button>\n");
      out.write("                                <button onclick=\"increaseQuantity(");
      out.print( cartItem.getProductId() );
      out.write(")\" class=\"btn btn-sm btn-outline-primary\">+</button>\n");
      out.write("                            </div>\n");
      out.write("                            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/CheckoutServlet\" method=\"post\">\n");
      out.write("                                <input type=\"hidden\" name=\"productId\" value=\"");
      out.print( cartItem.getProductId() );
      out.write("\">\n");
      out.write("                                <input type=\"hidden\" name=\"quantity\" value=\"");
      out.print( cartItem.getQuantity() );
      out.write("\">\n");
      out.write("                                <input type=\"hidden\" name=\"userId\" value=\"");
      out.print( session.getAttribute("userId") );
      out.write("\">\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary\">Buy Now</button>\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            ");

                }
            } else {
            
      out.write("\n");
      out.write("            <div class=\"col\">\n");
      out.write("                <p>Your cart is empty</p>\n");
      out.write("            </div>\n");
      out.write("            ");

            }
            
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <script>\n");
      out.write("        function decreaseQuantity(productId) {\n");
      out.write("            var quantityElement = document.getElementById('quantity_' + productId);\n");
      out.write("            var currentQuantity = parseInt(quantityElement.innerText);\n");
      out.write("            if (currentQuantity > 1) {\n");
      out.write("                quantityElement.innerText = currentQuantity - 1;\n");
      out.write("                updateQuantityInCart(productId, currentQuantity - 1);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function increaseQuantity(productId) {\n");
      out.write("            var quantityElement = document.getElementById('quantity_' + productId);\n");
      out.write("            var currentQuantity = parseInt(quantityElement.innerText);\n");
      out.write("            quantityElement.innerText = currentQuantity + 1;\n");
      out.write("            updateQuantityInCart(productId, currentQuantity + 1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function updateQuantityInCart(productId, newQuantity) {\n");
      out.write("            // Send an AJAX request to update the quantity in the cart\n");
      out.write("            fetch('UpdateCartServlet?productId=' + productId + '&quantity=' + newQuantity, {\n");
      out.write("                method: 'POST'\n");
      out.write("            })\n");
      out.write("            .then(response => response.json())\n");
      out.write("            .then(data => {\n");
      out.write("                if (!data.success) {\n");
      out.write("                    alert('Failed to update quantity in cart');\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("            .catch(error => {\n");
      out.write("                console.error('Error:', error);\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    <!-- Add Bootstrap JavaScript and dependencies (optional) -->\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
