/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2024-05-14 07:21:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import utils.Utilities;
import utils.Utilities;

public final class Contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/pages/Header.jsp", Long.valueOf(1715671287572L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("utils.Utilities");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<link rel=\"icon\"\n");
      out.write("    href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Images/pixelprinter-high-resolution-logo.png\"\n");
      out.write("    type=\"image/png\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<title>\n");
      out.write("    ");
      out.write("\n");
      out.write("    Printer Design\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");
 String currentPage = request.getRequestURI();
       if (currentPage.endsWith("Index.jsp")) { 
      out.write("\n");
      out.write("           | Home\n");
      out.write("       ");
 } else if (currentPage.endsWith("DisplayProductToCustomerServlet")) { 
      out.write("\n");
      out.write("           | Product\n");
      out.write("       ");
 } else if (currentPage.endsWith("Contact.jsp")) { 
      out.write("\n");
      out.write("           | About Us\n");
      out.write("       ");
 } else if (currentPage.endsWith("Login.jsp")) { 
      out.write("\n");
      out.write("           | Login\n");
      out.write("       ");
 } else if (currentPage.endsWith("LogoutServlet")) { 
      out.write("\n");
      out.write("           | Logout\n");
      out.write("       ");
 } 
      out.write("\n");
      out.write("</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("    href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("    href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/Header.css\" />\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    <section id=\"header\" class=\"header\">\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pages/Index.jsp\"><img\n");
      out.write("            src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Images/logo.png\" class=\"logo\"\n");
      out.write("            style=\"width: 120px; height: auto;\"></a>\n");
      out.write("        <nav class=\"navbar\">\n");
      out.write("            <a class=\"active\"\n");
      out.write("                href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pages/Index.jsp\">Home</a> <a\n");
      out.write("                href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/DisplayProductToCustomerServlet\">Product</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pages/Contact.jsp\">About\n");
      out.write("                Us</a> \n");
      out.write("            ");
 
            if (session.getAttribute("username") == null) {
            
      out.write("\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pages/Login.jsp\">Login</a>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogoutServlet\">Logout</a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </nav>\n");
      out.write("        \n");
      out.write("        <div class=\"icons\">\n");
      out.write("            <div id=\"menu-btn\" class=\"fas fa-bars\"></div>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/UserProfile\" class=\"fas fa-user-circle\"></a> \n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/SearchServlet\" class=\"fas fa-search\"></a> \n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/DisplayCart\" class=\"fas fa-shopping-cart\"></a>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Printer Design </title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/contact.css\" />\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("     <div class=\"About_us\">\r\n");
      out.write("        <div class =\"Printer\" style=\"margin-top: 30px;\">\r\n");
      out.write("            <img src=\"https://nypost.com/wp-content/uploads/sites/2/2023/03/printerfeat.jpg?quality=75&strip=all&w=1200\"style=\"width: 650px; height: 350px;\">\r\n");
      out.write("       </div>\r\n");
      out.write("     </div> \r\n");
      out.write("\r\n");
      out.write("    <div class=\"Para_blog\">\r\n");
      out.write("        <p>\r\n");
      out.write("            PixelPrinter is a leading provider of high-quality printing solutions, catering to the needs of individuals and businesses alike. \r\n");
      out.write("            With years of experience in the industry, we have established ourselves as a reliable and trusted name in the printing market. \r\n");
      out.write("            Our dedicated team of professionals is committed to delivering exceptional products and services to our valued customers.\r\n");
      out.write("            At PixelPrinter, we specialize in offering a wide range of printing solutions that meet the diverse requirements of our clients.\r\n");
      out.write("            Whether you need professional-grade printers for your office or personal printers for home use, we have got you covered. \r\n");
      out.write("            We also provide a comprehensive selection of printing accessories, ink cartridges, and paper supplies to support your printing needs.\r\n");
      out.write("            We understand the importance of quality and reliability when it comes to printing. That's why we partner with renowned printer brands and ensure that our product \r\n");
      out.write("            lineup consists of top-notch printers known for their performance and durability. We believe in delivering printing solutions that consistently produce outstanding results, \r\n");
      out.write("            allowing you to unleash your creativity and achieve professional-grade prints.\r\n");
      out.write("        </p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <br>\r\n");
      out.write("    <br>\r\n");
      out.write("    <div class=\"message-from-backend\">\r\n");
      out.write("		");
 if (session.getAttribute(Utilities.Successfully_Stored_Message) != null) { 
      out.write("\r\n");
      out.write("		<div class=\"alert alert-success\" role=\"alert\">\r\n");
      out.write("			");
      out.print( session.getAttribute(Utilities.Successfully_Stored_Message) );
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		");
 } else if (request.getAttribute(Utilities.ERROR_MESSAGE) != null) {
                  if (request.getAttribute(Utilities.ERROR_MESSAGE).equals(Utilities.INCORRECT_FORM_DATA_MESSAGE)) { 
      out.write("\r\n");
      out.write("		<div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("			");
      out.print( request.getAttribute(Utilities.ERROR_MESSAGE) );
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		");
   } else if (request.getAttribute(Utilities.ERROR_MESSAGE).equals(Utilities.SERVER_ERROR_MESSAGE)) { 
      out.write("\r\n");
      out.write("		<div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("			");
      out.print( request.getAttribute(Utilities.ERROR_MESSAGE) );
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		");
   }
                  } 
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("    <div class=\"containerclass\">\r\n");
      out.write("        <div class=\"content\" >\r\n");
      out.write("            <div class=\"left\">\r\n");
      out.write("                <!-- Address Details -->\r\n");
      out.write("                <div class=\"address details\" >\r\n");
      out.write("                    <i class=\"fas fa-map-marker-alt\"></i>\r\n");
      out.write("                    <div class=\"topic\">Address</div>\r\n");
      out.write("                    <div class=\"text-one\">Damak </div>\r\n");
      out.write("                    <div class=\"text-two\">Jhapa</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Phone Details -->\r\n");
      out.write("                <div class=\"phone details\">\r\n");
      out.write("                    <i class=\"fas fa-phone-alt\"></i>\r\n");
      out.write("                    <div class=\"topic\">Phone</div>\r\n");
      out.write("                    <div class=\"text-one\">(977) 9842630796</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Email Details -->\r\n");
      out.write("                <div class=\"email details\">\r\n");
      out.write("                    <i class=\"fas fa-envelope\"></i>\r\n");
      out.write("                    <div class=\"topic\">Email</div>\r\n");
      out.write("                    <div class=\"text-one\">pixelPrinter686@gmail.com</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Contact Form -->\r\n");
      out.write("            <div class=\"right\" style=\"margin-top:80px;\">\r\n");
      out.write("                <div class=\"topic-text\">Send us a message</div>\r\n");
      out.write("                <p>If you have any queries regarding our products or overall system, you can contact us here.</p>\r\n");
      out.write("                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StoreContactUsMessage\" method=\"post\" onsubmit=\"validateform()\">\r\n");
      out.write("                    <div class=\"input-box\">\r\n");
      out.write("                        <input name=\"name\" type=\"text\" id=\"name\" placeholder=\"Enter your name\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"input-box\">\r\n");
      out.write("                        <input name=\"email\" type=\"text\" id=\"email\" placeholder=\"Enter your email\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"input-box\">\r\n");
      out.write("						<input type=\"tel\" id=\"phoneNumber\" placeholder=\"Phone Number\"\r\n");
      out.write("							name=\"phone_Num\">\r\n");
      out.write("					</div>\r\n");
      out.write("                    <div class=\"input-box message-box\">\r\n");
      out.write("                        <textarea name=\"message\" id=\"message\" placeholder=\"write us a message\" rows=\"4\" cols=\"50\" required></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"button\">\r\n");
      out.write("                        <button type=\"submit\">Send Now</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("<!-- \r\n");
      out.write("    <script>\r\n");
      out.write("        function validateform() {\r\n");
      out.write("            var name = document.getElementById(\"name\").value;\r\n");
      out.write("            var email = document.getElementById(\"email\").value;\r\n");
      out.write("            alert(\"Your message has been sent\");\r\n");
      out.write("            console.log(\"Name: \" + name);\r\n");
      out.write("            console.log(\"Email: \" + email);\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("     -->     \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
